version: 0.1

phases:
  install:
    commands:
      - echo "Updating AWS CLI..."
      - pip install --upgrade awscli
      
      - echo "Create output directory"
      - mkdir out

      - echo "Installing Mustache Globally"
      - npm install -g mustache

  pre_build:
    commands:
      - echo "Creating AWS Config file"
      - node -e 'console.log(JSON.stringify(process.env))' > out/build.json

  build:
    commands:
      - echo "Compiling API template..."
      - mustache out/build.json swagger.yaml > out/swagger.yaml

      - echo "Compiling Cloudformation, Bucket " $ARTIFACT_STORE
      - aws cloudformation package --template-file sam.yaml --s3-prefix build --s3-bucket $ARTIFACT_STORE --output-template-file out/template.yaml      

      - echo "Copying configuration"
      - cp -R .noths/.config/* out/

      - echo "Listing Output"
      - ls -lR out/

artifacts:
  type: zip
  discard-paths: yes
  files:
    - out/**/*
