AWSTemplateFormatVersion: 2010-09-09

Description: Product API Monitoring Dashboard

Parameters:

  DashboardName:
    Type: String

  RestApiName:
    Type: String

  RestApiStage:
    Type: String

Resources:

  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Ref DashboardName
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "view": "timeSeries",
                "stacked": false,
                "metrics": [
                  [
                    "AWS/ApiGateway", "Count", "ApiName", "${RestApiName}", "Resource", "/health", "Stage", "${RestApiStage}", "Method", "GET",
                    { "stat": "Sum", "label": "Requests", "color": "#2ca02c" }
                  ],
                  [
                    ".", "4XXError", ".", ".", ".", ".", ".", ".", ".", ".",
                    { "stat": "Sum", "label": "4XX" }
                  ],
                  [
                    ".", "5XXError", ".", ".", ".", ".", ".", ".", ".", ".",
                    { "stat": "Sum", "color": "#d62728", "label": "5XX" }
                  ]
                ],
                "region": "${AWS::Region}",
                "period": 300,
                "title": "Health Requests",
                "annotations": {
                  "horizontal": [
                    {
                      "color": "#98df8a",
                      "label": "Route 53 Health Check (5 Minutes)",
                      "value": 30
                    }
                  ]
                }
              }
            }
          ]
        }

Outputs:

  DashboardUrl:
    Description: AWS Console HTTPs URL for Monitoring
    Value:
      Fn::Sub: https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${Dashboard}
