---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Testing a small API deployment

Parameters:
  Stage:
    Type: String
    Description: The default stage
    Default: staging

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./out/swagger.yaml
      StageName: !Ref Stage
      Variables:
        ExecutionRoleName:
          Ref: ApiGatewayExecutionRole
        ProductsTable:
          Ref: ProductsTable

  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ApiGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole

  ApiGatewayExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: APIPermissions
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Scan
            Resource: !GetAtt ProductsTable.Arn
      Roles:
        - Ref: ApiGatewayExecutionRole

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Stage}"