---
AWSTemplateFormatVersion: '2010-09-09'
Description: Product API Monitoring Dashboard

Parameters:
  DashboardName:
    Type: String
  RestApiName:
    Type: String
  RestApiStage:
    Type: String
  ProductsTable:
    Type: String
  ProductUpdateTopic:
    Type: String 
  WriteToDynamoLambdaFunction:
    Type: String

Resources:
  # Docs for CloudWatch::Alarm resource http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#w2ab2c21c10d187c15
  LatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: Latency Alert
      AlarmDescription: "Latency is >= 100,000 for 1 minute (#product-api-alerts)"
      Namespace: ProductApi/ApiGateway
      ActionsEnabled: true
      AlarmActions:
        - arn:aws:sns:eu-west-1:235649422648:spike-alarm
      OKActions: 
        - arn:aws:sns:eu-west-1:235649422648:spike-alarm
      MetricName: Latency
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Period: 60 #I.e. 60 seconds.
      EvaluationPeriods: 2
      Statistic: Average
      Threshold: 1
      Unit: Milliseconds
      TreatMissingData: breaching
      
  Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Ref DashboardName
      DashboardBody: !Sub |
        {
            "widgets": [
                {
                    "type": "metric",
                    "x": 0,
                    "y": 0,
                    "width": 24,
                    "height": 3,
                    "properties": {
                        "view": "singleValue",
                        "metrics": [
                            [ "AWS/ApiGateway", "Count", "ApiName", "${RestApiName}", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "5XXError", ".", ".", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "4XXError", ".", ".", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "Latency", ".", ".", { "period": 86400 } ],
                            [ ".", "IntegrationLatency", ".", ".", { "period": 86400 } ]
                        ],
                        "region": "eu-west-1",
                        "period": 300,
                        "title": "Product API 24hr Summary"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 3,
                    "width": 24,
                    "height": 3,
                    "properties": {
                        "view": "singleValue",
                        "metrics": [
                            [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${ProductsTable}", { "period": 86400 } ],
                            [ ".", "ConsumedWriteCapacityUnits", ".", ".", { "period": 86400 } ],
                            [ ".", "ProvisionedWriteCapacityUnits", ".", ".", { "period": 86400 } ],
                            [ ".", "ProvisionedReadCapacityUnits", ".", ".", { "period": 86400 } ]
                        ],
                        "region": "eu-west-1",
                        "title": "DynamoDB Products Table Summary",
                        "period": 300
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 9,
                    "width": 24,
                    "height": 3,
                    "properties": {
                        "view": "singleValue",
                        "metrics": [
                            [ "AWS/SNS", "NumberOfMessagesPublished", "TopicName", "${ProductUpdateTopic}", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "NumberOfNotificationsDelivered", ".", ".", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "NumberOfNotificationsFailed", ".", ".", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "PublishSize", ".", ".", { "period": 86400 } ]
                        ],
                        "region": "eu-west-1",
                        "period": 300,
                        "title": "SNS ProductUpdate Topic Summary"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 12,
                    "width": 24,
                    "height": 3,
                    "properties": {
                        "view": "singleValue",
                        "metrics": [
                            [ "AWS/Lambda", "Invocations", "FunctionName", "${WriteToDynamoLambdaFunction}", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "Errors", ".", ".", { "stat": "Sum", "period": 86400 } ],
                            [ ".", "Throttles", ".", ".", { "period": 86400, "stat": "Sum" } ],
                            [ ".", "Duration", ".", ".", { "period": 86400 } ]
                        ],
                        "region": "eu-west-1",
                        "title": "Write Product To DyanmoDB Lambda",
                        "period": 300
                    }
                }
            ]
        }
Outputs:
  DashboardUrl:
    Description: AWS Console HTTPs URL for Monitoring
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${Dashboard}"
